name: Build Application

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        include:
          # - os: ubuntu-latest
          #   platform: linux
          #   arch: amd64
          # - os: ubuntu-latest
          #   platform: linux
          #   arch: arm64
          # - os: macos-latest
          #   platform: darwin
          #   arch: amd64
          - os: macos-latest
            platform: darwin
            arch: arm64
          # - os: windows-latest
          #   platform: windows
          #   arch: amd64
          # - os: windows-latest
          #   platform: windows
          #   arch: arm64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.0'
        cache: true

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: 'yarn'
        cache-dependency-path: frontend/yarn.lock

    - name: Install Wails CLI
      run: |
        go install github.com/wailsapp/wails/v3/cmd/wails3@v3.0.0-alpha.36

    - name: Build application
      run: |
        wails3 task package
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: local-proxy-${{ matrix.platform }}-${{ matrix.arch }}
        path: |
          bin/local-proxy*
          bin/*.app
          bin/*.exe
          bin/*.AppImage
          bin/*.deb
          bin/*.rpm
          bin/*.msi
        retention-days: 30